//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_osnova_2__EF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notebooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notebooks()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int notebook_id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string storage_capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders {private get; set; }
    }
}
