//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_osnova_2__EF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int sale_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        public virtual Orders Orders {private get; set; }
    }
}
